//! Converting between Rust types and WCL [`Value`]s at the builtin
//! boundary.
//!
//! [`FromValue`] reads an argument, [`IntoValue`] writes a return value,
//! and [`IntoValueResult`] lets a builtin be fallible. The scalar impls
//! are generated by macro because there is one per numeric width and
//! they differ only in which `Value` variant they match.

use crate::numeric::for_each_numeric_variant;
use crate::value::Value;

use super::builtin::{FromValue, IntoValue};

// ─── FromValue impls ─────────────────────────────────────────────────

/// Implement [`FromValue`] for a scalar Rust type by matching the
/// corresponding `Value` variant.
macro_rules! from_value_scalar {
    ($t:ty, $variant:ident) => {
        impl FromValue for $t {
            fn from_value(v: &Value) -> Result<Self, String> {
                match v {
                    Value::$variant(n) => Ok(*n),
                    other => Err(format!(
                        "expected {}, found {}",
                        stringify!($t),
                        other.type_name()
                    )),
                }
            }
        }
    };
}

from_value_scalar!(bool, Bool);
for_each_numeric_variant!(from_value_scalar);

impl FromValue for String {
    fn from_value(v: &Value) -> Result<Self, String> {
        match v {
            Value::Utf8(s) | Value::Ascii(s) => Ok(s.clone()),
            other => Err(format!("expected utf8 string, found {}", other.type_name())),
        }
    }
}

impl FromValue for Value {
    fn from_value(v: &Value) -> Result<Self, String> {
        Ok(v.clone())
    }
}

/// Strongly-typed parameter for builtins that consume a
/// [`Value::DataPath`] handle. Carries the same `kind` tag and `segments`
/// as the underlying value.
#[derive(Debug, Clone)]
pub struct DataPath {
    /// The underlying `DataKind` tag.
    pub kind: String,
    /// Dotted path that re-resolves the target from the document root.
    pub segments: Vec<String>,
}

impl FromValue for DataPath {
    fn from_value(v: &Value) -> Result<Self, String> {
        match v {
            Value::DataPath { kind, segments } => Ok(Self {
                kind: kind.clone(),
                segments: segments.clone(),
            }),
            other => Err(format!(
                "expected data path (e.g. a type or block reference), found {}",
                other.type_name()
            )),
        }
    }
}

impl<T> FromValue for Option<T>
where
    T: FromValue,
{
    fn from_value(v: &Value) -> Result<Self, String> {
        if matches!(v, Value::None) {
            Ok(None)
        } else {
            T::from_value(v).map(Some)
        }
    }
}

impl<T> FromValue for Vec<T>
where
    T: FromValue,
{
    fn from_value(v: &Value) -> Result<Self, String> {
        match v {
            Value::List(items) => items.iter().map(T::from_value).collect(),
            other => Err(format!("expected list, found {}", other.type_name())),
        }
    }
}

// ─── IntoValue impls ─────────────────────────────────────────────────

/// Implement [`IntoValue`] for a scalar Rust type by wrapping it in
/// the corresponding `Value` variant.
macro_rules! into_value_scalar {
    ($t:ty, $variant:ident) => {
        impl IntoValue for $t {
            fn into_value(self) -> Value {
                Value::$variant(self)
            }
        }
    };
}

into_value_scalar!(bool, Bool);
for_each_numeric_variant!(into_value_scalar);

impl IntoValue for String {
    fn into_value(self) -> Value {
        Value::Utf8(self)
    }
}

impl IntoValue for &str {
    fn into_value(self) -> Value {
        Value::Utf8(self.to_string())
    }
}

impl IntoValue for () {
    fn into_value(self) -> Value {
        Value::None
    }
}

impl IntoValue for Value {
    fn into_value(self) -> Value {
        self
    }
}

impl<T> IntoValue for Option<T>
where
    T: IntoValue,
{
    fn into_value(self) -> Value {
        match self {
            Some(t) => t.into_value(),
            None => Value::None,
        }
    }
}

impl<T> IntoValue for Vec<T>
where
    T: IntoValue,
{
    fn into_value(self) -> Value {
        Value::list(self.into_iter().map(T::into_value).collect())
    }
}
