[package]
name = "wcl_lang"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WCL language library: parser and AST"

[dependencies]
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = "3"

[[bench]]
name = "parse"
harness = false
