[package]
name = "wcl_lang-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.wcl_lang]
path = ".."

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false

[[bin]]
name = "eval"
path = "fuzz_targets/eval.rs"
test = false
doc = false

[[bin]]
name = "format_round_trip"
path = "fuzz_targets/format_round_trip.rs"
test = false
doc = false
