[workspace]
resolver = "2"
members = ["crates/wcl", "crates/wcl_lang", "crates/wcl_lsp", "crates/wcl_wdoc"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/wiltaylor/wcl"

[workspace.dependencies]
wcl_lang = { path = "crates/wcl_lang", version = "0.0.0" }
wcl_lsp = { path = "crates/wcl_lsp", version = "0.0.0" }
wcl_wdoc = { path = "crates/wcl_wdoc", version = "0.0.0" }
clap = { version = "4", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
criterion = { version = "0.8", features = ["html_reports"] }
assert_cmd = "2"
predicates = "3"
tempfile = "3"
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "io-util", "net", "sync"] }
axum = { version = "0.8", default-features = false, features = ["tokio", "http1", "ws"] }
notify = "8"
ignore = "0.4"
rust-embed = "8"
tower = { version = "0.5", default-features = false, features = ["util"] }
dashmap = "6"
ropey = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
insta = "1"
proptest = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
todo = "warn"
dbg_macro = "warn"

[profile.release]
lto = true
codegen-units = 1
