[workspace]
resolver = "2"
members = ["crates/wcl", "crates/wcl_lang", "crates/wcl_lsp"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/wiltaylor/wcl"

[workspace.dependencies]
wcl_lang = { path = "crates/wcl_lang", version = "0.0.0" }
wcl_lsp = { path = "crates/wcl_lsp", version = "0.0.0" }
clap = { version = "4", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
criterion = { version = "0.5", features = ["html_reports"] }
assert_cmd = "2"
predicates = "3"
tempfile = "3"
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "io-util", "net", "sync"] }
dashmap = "6"
ropey = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

[profile.release]
lto = true
codegen-units = 1
