[book]
authors = ["Wil"]
language = "en"
src = "src"
title = "WCL -- Wil's Configuration Language"

[build]
build-dir = "build"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/wiltaylor/wcl/docs"
additional-js = ["wcl-grammar.js", "wcl-highlight.js"]
site-url = "/docs/"
