//! Build script: bundle the vendored SVG icon packs into the binary.
//!
//! For each directory under `assets/icons/<pack>/` we concatenate every
//! `*.svg` into a single `$OUT_DIR/<pack>.bin` blob and emit a
//! `$OUT_DIR/icon_manifest.rs` describing each pack: one `include_bytes!`
//! of its blob plus a name-sorted `(name, offset, len)` index. `icons.rs`
//! `include!`s the manifest and resolves an icon by binary-searching the
//! index, then slicing the blob — no per-icon `include_bytes!` (which
//! would mean thousands of macro expansions) and no runtime allocation.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icons_root = manifest_dir.join("assets/icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Re-run whenever any vendored icon changes (added / removed / edited).
    println!("cargo:rerun-if-changed={}", icons_root.display());
    println!("cargo:rerun-if-changed=build.rs");

    // Discover pack directories deterministically (sorted) so the
    // generated manifest is stable across builds.
    let mut packs: Vec<PathBuf> = fs::read_dir(&icons_root)
        .unwrap_or_else(|e| panic!("read {}: {e}", icons_root.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    packs.sort();

    let mut manifest = String::new();
    manifest.push_str("// @generated by build.rs — do not edit.\n");
    manifest.push_str("pub(crate) static ICON_PACKS: &[IconPack] = &[\n");

    for pack_dir in &packs {
        let pack_name = pack_dir
            .file_name()
            .and_then(|n| n.to_str())
            .expect("pack dir name");
        let (blob, index) = bundle_pack(pack_dir);

        let blob_path = out_dir.join(format!("{pack_name}.bin"));
        fs::write(&blob_path, &blob)
            .unwrap_or_else(|e| panic!("write {}: {e}", blob_path.display()));

        writeln!(manifest, "    IconPack {{").unwrap();
        writeln!(manifest, "        name: {pack_name:?},").unwrap();
        writeln!(
            manifest,
            "        blob: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{pack_name}.bin\")),"
        )
        .unwrap();
        manifest.push_str("        index: &[\n");
        for (name, offset, len) in &index {
            writeln!(manifest, "            ({name:?}, {offset}, {len}),").unwrap();
        }
        manifest.push_str("        ],\n    },\n");
    }

    manifest.push_str("];\n");

    let manifest_path = out_dir.join("icon_manifest.rs");
    fs::write(&manifest_path, manifest)
        .unwrap_or_else(|e| panic!("write {}: {e}", manifest_path.display()));
}

/// Concatenate a pack's `*.svg` files into one blob, returning the blob
/// and a name-sorted `(stem, offset, len)` index into it. Names are the
/// file stems; a `BTreeMap` keeps them sorted (so the generated index
/// supports `binary_search_by_key`).
fn bundle_pack(dir: &Path) -> (Vec<u8>, Vec<(String, usize, usize)>) {
    let mut svgs: BTreeMap<String, String> = BTreeMap::new();
    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("read {}: {e}", dir.display())) {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("svg") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let content =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        svgs.insert(stem.to_string(), content);
    }

    let mut blob = Vec::new();
    let mut index = Vec::with_capacity(svgs.len());
    for (name, content) in svgs {
        let offset = blob.len();
        blob.extend_from_slice(content.as_bytes());
        index.push((name, offset, content.len()));
    }
    (blob, index)
}
