[package]
name = "wcl_wdoc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WCL-driven static site / document generator (library)"

[dependencies]
wcl_lang = { workspace = true }
miette = { workspace = true }
regex = "1"
tokio = { workspace = true, features = ["fs", "signal"] }
axum = { workspace = true }
notify = { workspace = true }
tempfile = { workspace = true }
syntect = { version = "5", default-features = false, features = ["default-fancy", "html"] }
two-face = { version = "0.5", default-features = false, features = ["syntect-fancy"] }

[lints]
workspace = true
