[package]
name = "wcl_wdoc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WCL-driven static site / document generator (library)"

[dependencies]
wcl_lang = { workspace = true }
miette = { workspace = true }
tokio = { workspace = true, features = ["fs", "signal"] }
axum = { workspace = true }
notify = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
