//! The `timeline` renderer — a real-time axis.
//!
//! A timeline tracks calendar time: authors give ISO date strings
//! (`"2026-03-15"`, `"2026-03-15 14:30"`), pick a `unit` (minute … year),
//! and the axis shows tick points at calendar boundaries with items and
//! event cards pinned to explicit dates. Calendar math (variable month
//! lengths, leap years, month/year stepping) can't be done in WCL, so —
//! like `map` / `tilemap` — the timeline is `@native` (see
//! [`crate::native`]) and the whole shape is drawn here. Positions come
//! from a monotonic scalar (julian-day × 86400 + seconds); ticks are
//! generated by walking real calendar boundaries with the `time` crate.

use std::collections::BTreeMap;

use time::{Date, Duration, Month, PrimitiveDateTime, Time};
use wcl_lang::{Block, Value, VariantPayload};

use crate::blocks::diagram::card::render_card_foreign;
use crate::render::{
    field_f64, field_i64, field_id, field_symbol, field_utf8, field_utf8_list, map_utf8,
};
use crate::svg::{RenderCtx, emit_circle, emit_line, emit_text};

/// Abbreviated month names used on axis labels.
const MON: [&str; 12] = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

#[derive(Clone, Copy, PartialEq)]
/// The granularity a timeline axis is stepped in.
enum Unit {
    /// Minute granularity.
    Minutes,
    /// Hour granularity.
    Hours,
    /// Day granularity.
    Days,
    /// Week granularity.
    Weeks,
    /// Month granularity.
    Months,
    /// Year granularity.
    Years,
}

/// Render a `@block("timeline")` into its full SVG (axis, ticks, phases,
/// items, and `<foreignObject>` event cards).
pub(crate) fn render_timeline(
    block: &Block<'_>,
    ctx: RenderCtx<'_>,
    _parent_w: f64,
    _parent_h: f64,
) -> String {
    let is_h = field_symbol(block, "direction").as_deref() != Some("vertical");
    let title = field_utf8(block, "title").unwrap_or_default();
    let (x, y) = (
        field_f64(block, "x").unwrap_or(0.0),
        field_f64(block, "y").unwrap_or(0.0),
    );
    let w = field_f64(block, "width").unwrap_or(480.0);
    let h = field_f64(block, "height").unwrap_or(200.0);

    // ── Gather dated events ────────────────────────────────────────
    let items = list_field(block, "items");
    let phases = list_field(block, "phases");
    let cards: Vec<Block<'_>> = block.blocks().filter(|b| b.kind() == "card").collect();

    let mut stamps: Vec<f64> = Vec::new();
    for v in &items {
        if let Some((_, m)) = variant(v)
            && let Some(s) = map_utf8(m, "on").and_then(|d| parse_stamp(&d))
        {
            stamps.push(s);
        }
    }
    for v in &phases {
        if let Some((_, m)) = variant(v) {
            for k in ["from", "to"] {
                if let Some(s) = map_utf8(m, k).and_then(|d| parse_stamp(&d)) {
                    stamps.push(s);
                }
            }
        }
    }
    for c in &cards {
        if let Some(s) = field_utf8(c, "on").and_then(|d| parse_stamp(&d)) {
            stamps.push(s);
        }
    }

    // ── Fit the scale [lo, hi] ─────────────────────────────────────
    let start = field_utf8(block, "start").and_then(|d| parse_stamp(&d));
    let end = field_utf8(block, "end").and_then(|d| parse_stamp(&d));
    let data_lo = stamps.iter().cloned().fold(f64::INFINITY, f64::min);
    let data_hi = stamps.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let mut lo = start.unwrap_or(data_lo);
    let mut hi = end.unwrap_or(data_hi);
    let has_scale = lo.is_finite() && hi.is_finite();
    if !has_scale {
        // No dates at all: draw a bare axis.
        lo = 0.0;
        hi = 1.0;
    } else if (hi - lo).abs() < 1.0 {
        // A single instant: open a one-unit window around it.
        hi = lo + 86400.0;
    }
    let span = (hi - lo).max(1.0);
    let frac = |s: f64| (s - lo) / span;

    // ── Layout (ported from the original WCL geometry) ─────────────
    let title_h = if title.is_empty() { 6.0 } else { 22.0 };
    let amain = if is_h {
        y + title_h + (h - title_h) / 2.0
    } else {
        x + w / 2.0
    };
    let margin = 24.0;
    let alo = if is_h {
        x + margin
    } else {
        y + title_h + margin
    };
    let ahi = if is_h { x + w - margin } else { y + h - margin };
    let cross = if is_h { h - title_h } else { w };
    let ext = cross * 0.42;
    let px = |f: f64, perp: f64| {
        if is_h {
            alo + (ahi - alo) * f
        } else {
            amain + perp
        }
    };
    let py = |f: f64, perp: f64| {
        if is_h {
            amain + perp
        } else {
            alo + (ahi - alo) * f
        }
    };

    let mut out = String::new();

    // Title.
    if !title.is_empty() {
        out.push_str(&emit_text(
            &title,
            x + w / 2.0,
            y + 11.0,
            13.0,
            &cls(&["wdoc-chart-title"]),
            None,
            None,
        ));
    }

    // Phases: a boundary divider at `from` and `to` + a centred heading,
    // each cycling the palette.
    for (i, v) in phases.iter().enumerate() {
        let Some((_, m)) = variant(v) else { continue };
        let (Some(fa), Some(fb)) = (
            map_utf8(m, "from").and_then(|d| parse_stamp(&d)),
            map_utf8(m, "to").and_then(|d| parse_stamp(&d)),
        ) else {
            continue;
        };
        let (fa, fb) = (frac(fa), frac(fb));
        let fm = (fa + fb) / 2.0;
        let series = format!("wdoc-series-{}", i % 8 + 1);
        for f in [fa, fb] {
            out.push_str(&emit_line(
                &cls(&[series.as_str(), "wdoc-timeline-divider"]),
                px(f, -ext),
                py(f, -ext),
                px(f, ext),
                py(f, ext),
                None,
                None,
            ));
        }
        out.push_str(&emit_text(
            &map_utf8(m, "label").unwrap_or_default(),
            px(fm, -ext + 10.0),
            py(fm, -ext + 10.0),
            11.0,
            &cls(&[series.as_str(), "wdoc-timeline-phase-label"]),
            None,
            None,
        ));
    }

    // Axis spine.
    out.push_str(&emit_line(
        &cls(&["wdoc-axis"]),
        px(0.0, 0.0),
        py(0.0, 0.0),
        px(1.0, 0.0),
        py(1.0, 0.0),
        None,
        None,
    ));

    // Calendar ticks.
    if has_scale {
        let unit = unit_of(block, hi - lo);
        let every = field_i64(block, "every")
            .filter(|e| *e > 0)
            .unwrap_or_else(|| auto_every(unit, hi - lo));
        for (sc, label) in ticks(lo, hi, unit, every) {
            let f = frac(sc);
            out.push_str(&emit_line(
                &cls(&["wdoc-axis"]),
                px(f, -3.0),
                py(f, -3.0),
                px(f, 3.0),
                py(f, 3.0),
                None,
                None,
            ));
            out.push_str(&emit_text(
                &label,
                px(f, 12.0),
                py(f, 12.0),
                9.0,
                &cls(&["wdoc-axis-label"]),
                None,
                None,
            ));
        }
    }

    // Items: marker + lead line + label, auto-alternating sides.
    for (i, v) in items.iter().enumerate() {
        let Some((variant, m)) = variant(v) else {
            continue;
        };
        if variant != "On" && variant != "OnSided" {
            continue;
        }
        let Some(f) = map_utf8(m, "on").and_then(|d| parse_stamp(&d)).map(frac) else {
            continue;
        };
        let s = side_sign(map_symbol(m, "side").as_deref(), i);
        let lead = 20.0;
        out.push_str(&emit_line(
            &cls(&["wdoc-timeline-connector"]),
            px(f, 0.0),
            py(f, 0.0),
            px(f, s * lead),
            py(f, s * lead),
            None,
            None,
        ));
        out.push_str(&emit_circle(
            &cls(&["wdoc-timeline-marker"]),
            px(f, 0.0),
            py(f, 0.0),
            3.0,
            None,
            None,
            None,
        ));
        out.push_str(&emit_text(
            &map_utf8(m, "label").unwrap_or_default(),
            px(f, s * (lead + 9.0)),
            py(f, s * (lead + 9.0)),
            11.0,
            &cls(&["wdoc-timeline-label"]),
            None,
            None,
        ));
    }

    // Event cards: marker + lead line + a `<foreignObject>` box pinned to
    // the card's date, clamped inside the timeline box.
    for (i, c) in cards.iter().enumerate() {
        let Some(f) = field_utf8(c, "on").and_then(|d| parse_stamp(&d)).map(frac) else {
            continue;
        };
        let s = side_sign(field_symbol(c, "side").as_deref(), i);
        let near = s < 0.0;
        let lead = 14.0;
        let cw = field_f64(c, "width").unwrap_or(160.0);
        let ch = field_f64(c, "height").unwrap_or(90.0);
        let (mx, my) = (px(f, 0.0), py(f, 0.0));
        let raw_bx = if is_h {
            mx - cw / 2.0
        } else if near {
            amain - lead - cw
        } else {
            amain + lead
        };
        let raw_by = if is_h {
            if near {
                amain - lead - ch
            } else {
                amain + lead
            }
        } else {
            my - ch / 2.0
        };
        let bx = raw_bx.max(x).min((x + w - cw).max(x));
        let by = raw_by.max(y).min((y + h - ch).max(y));
        out.push_str(&emit_line(
            &cls(&["wdoc-timeline-connector"]),
            mx,
            my,
            px(f, s * lead),
            py(f, s * lead),
            None,
            None,
        ));
        out.push_str(&emit_circle(
            &cls(&["wdoc-timeline-marker"]),
            mx,
            my,
            3.0,
            None,
            None,
            None,
        ));
        let body: Vec<Block<'_>> = c.blocks().collect();
        out.push_str(&render_card_foreign(
            field_utf8(c, "title").as_deref(),
            &body,
            &field_utf8_list(c, "class"),
            field_id(c, "id").as_deref(),
            (bx, by, cw, ch),
            ctx,
        ));
    }

    out
}

/// Read a block field that holds a `list<…>` of union variants.
fn list_field<'a>(block: &Block<'a>, name: &str) -> Vec<Value> {
    match block.field(name).and_then(|f| f.value().ok()) {
        Some(Value::List(xs)) => xs.as_ref().clone(),
        _ => Vec::new(),
    }
}

/// Destructure a record-variant value into `(variant_name, fields)`.
fn variant(v: &Value) -> Option<(&str, &BTreeMap<String, Value>)> {
    if let Value::Variant {
        variant,
        payload: VariantPayload::Record(m),
        ..
    } = v
    {
        Some((variant.as_str(), m))
    } else {
        None
    }
}

/// Read a symbol entry out of a record, without its leading colon.
fn map_symbol(m: &BTreeMap<String, Value>, k: &str) -> Option<String> {
    match m.get(k) {
        Some(Value::Symbol(s)) => Some(s.clone()),
        _ => None,
    }
}

/// Perpendicular sign for an item/card: `:near` → -1, `:far` → +1, else
/// alternate by index.
fn side_sign(side: Option<&str>, i: usize) -> f64 {
    match side {
        Some("near") => -1.0,
        Some("far") => 1.0,
        _ if i.is_multiple_of(2) => -1.0,
        _ => 1.0,
    }
}

/// A ` class="…"` attribute string for the `emit_*` helpers.
fn cls(names: &[&str]) -> String {
    format!(" class=\"{}\"", names.join(" "))
}

// ── Date handling ──────────────────────────────────────────────────

/// Parse an ISO date / date-time (`YYYY-MM-DD[ |T]HH:MM[:SS]`) into a
/// monotonic scalar (seconds). `None` for anything unparseable.
fn parse_stamp(s: &str) -> Option<f64> {
    let s = s.trim().replacen('T', " ", 1);
    let mut parts = s.split_whitespace();
    let mut d = parts.next()?.split('-');
    let yr: i32 = d.next()?.parse().ok()?;
    let mo: u8 = d.next()?.parse().ok()?;
    let da: u8 = d.next()?.parse().ok()?;
    let (mut hh, mut mm, mut ss) = (0u8, 0u8, 0u8);
    if let Some(t) = parts.next() {
        let mut tp = t.split(':');
        hh = tp.next().and_then(|x| x.parse().ok())?;
        mm = tp.next().and_then(|x| x.parse().ok()).unwrap_or(0);
        ss = tp.next().and_then(|x| x.parse().ok()).unwrap_or(0);
    }
    let date = Date::from_calendar_date(yr, Month::try_from(mo).ok()?, da).ok()?;
    let time = Time::from_hms(hh, mm, ss).ok()?;
    Some(dt_scalar(&PrimitiveDateTime::new(date, time)))
}

/// Project a datetime onto the seconds scale the axis is laid out in.
fn dt_scalar(dt: &PrimitiveDateTime) -> f64 {
    dt.date().to_julian_day() as f64 * 86400.0
        + dt.hour() as f64 * 3600.0
        + dt.minute() as f64 * 60.0
        + dt.second() as f64
}

/// Invert [`dt_scalar`], or `None` when the value is out of range.
fn scalar_to_dt(s: f64) -> Option<PrimitiveDateTime> {
    let jd = (s / 86400.0).floor();
    let rem = s - jd * 86400.0;
    let date = Date::from_julian_day(jd as i32).ok()?;
    let hh = (rem / 3600.0).floor() as u8;
    let mm = ((rem % 3600.0) / 60.0).floor() as u8;
    let ss = (rem % 60.0).floor() as u8;
    let time = Time::from_hms(hh.min(23), mm.min(59), ss.min(59)).ok()?;
    Some(PrimitiveDateTime::new(date, time))
}

/// The tick unit: the author's `unit`, else auto-chosen for the span.
fn unit_of(block: &Block<'_>, span_secs: f64) -> Unit {
    match field_symbol(block, "unit").as_deref() {
        Some("minutes") => Unit::Minutes,
        Some("hours") => Unit::Hours,
        Some("days") => Unit::Days,
        Some("weeks") => Unit::Weeks,
        Some("months") => Unit::Months,
        Some("years") => Unit::Years,
        _ => {
            let days = span_secs / 86400.0;
            if days > 730.0 {
                Unit::Years
            } else if days > 75.0 {
                Unit::Months
            } else if days > 21.0 {
                Unit::Weeks
            } else if days > 2.0 {
                Unit::Days
            } else if span_secs > 7200.0 {
                Unit::Hours
            } else {
                Unit::Minutes
            }
        }
    }
}

/// Nominal length of one unit in seconds. Approximate for months and
/// years, which is fine — it is only used to choose a step size.
fn unit_secs(u: Unit) -> f64 {
    match u {
        Unit::Minutes => 60.0,
        Unit::Hours => 3600.0,
        Unit::Days => 86400.0,
        Unit::Weeks => 604_800.0,
        Unit::Months => 2_629_800.0,
        Unit::Years => 31_557_600.0,
    }
}

/// Pick a tick interval (in `unit`s) so the axis carries ~6–12 ticks.
fn auto_every(u: Unit, span_secs: f64) -> i64 {
    let raw = (span_secs / unit_secs(u)).max(1.0);
    let ladder: &[i64] = match u {
        Unit::Minutes => &[1, 2, 5, 10, 15, 30, 60],
        Unit::Hours => &[1, 2, 3, 6, 12, 24],
        Unit::Days => &[1, 2, 5, 7, 14, 28],
        Unit::Weeks => &[1, 2, 4, 8],
        Unit::Months => &[1, 2, 3, 6, 12],
        Unit::Years => &[1, 2, 5, 10, 20, 50],
    };
    for &e in ladder {
        if raw / e as f64 <= 12.0 {
            return e;
        }
    }
    *ladder.last().unwrap()
}

/// Walk calendar boundaries from `floor(lo)` by `every` units, yielding
/// `(scalar, label)` for every tick within `[lo, hi]`.
fn ticks(lo: f64, hi: f64, u: Unit, every: i64) -> Vec<(f64, String)> {
    let Some(mut cur) = scalar_to_dt(lo).map(|dt| floor_to_unit(&dt, u)) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for _ in 0..256 {
        let sc = dt_scalar(&cur);
        if sc > hi + 0.5 {
            break;
        }
        if sc >= lo - 0.5 {
            out.push((sc, tick_label(&cur, u)));
        }
        cur = step(&cur, u, every);
    }
    out
}

/// Round a datetime down to a unit boundary, so ticks land on round
/// numbers.
fn floor_to_unit(dt: &PrimitiveDateTime, u: Unit) -> PrimitiveDateTime {
    let (d, t) = (dt.date(), dt.time());
    let mid = |date: Date| PrimitiveDateTime::new(date, Time::MIDNIGHT);
    match u {
        Unit::Minutes => PrimitiveDateTime::new(
            d,
            Time::from_hms(t.hour(), t.minute(), 0).unwrap_or(Time::MIDNIGHT),
        ),
        Unit::Hours => {
            PrimitiveDateTime::new(d, Time::from_hms(t.hour(), 0, 0).unwrap_or(Time::MIDNIGHT))
        }
        Unit::Days => mid(d),
        Unit::Weeks => {
            let back = d.weekday().number_days_from_monday() as i64;
            mid(d) - Duration::days(back)
        }
        Unit::Months => mid(Date::from_calendar_date(d.year(), d.month(), 1).unwrap_or(d)),
        Unit::Years => mid(Date::from_calendar_date(d.year(), Month::January, 1).unwrap_or(d)),
    }
}

/// Advance a datetime by `every` units.
fn step(dt: &PrimitiveDateTime, u: Unit, every: i64) -> PrimitiveDateTime {
    match u {
        Unit::Minutes => *dt + Duration::minutes(every),
        Unit::Hours => *dt + Duration::hours(every),
        Unit::Days => *dt + Duration::days(every),
        Unit::Weeks => *dt + Duration::weeks(every),
        Unit::Months => add_months(dt, every),
        Unit::Years => add_months(dt, every * 12),
    }
}

/// Add months, clamping the day when the target month is shorter.
fn add_months(dt: &PrimitiveDateTime, n: i64) -> PrimitiveDateTime {
    let total = dt.year() as i64 * 12 + (u8::from(dt.month()) as i64 - 1) + n;
    let ny = total.div_euclid(12) as i32;
    let nm = (total.rem_euclid(12) + 1) as u8;
    let day = (dt.day()).min(days_in(ny, nm));
    let date = Date::from_calendar_date(ny, Month::try_from(nm).unwrap_or(Month::January), day)
        .unwrap_or_else(|_| dt.date());
    PrimitiveDateTime::new(date, dt.time())
}

/// Whether a year is a leap year.
fn is_leap(y: i32) -> bool {
    (y % 4 == 0 && y % 100 != 0) || y % 400 == 0
}

/// Days in a given month.
fn days_in(y: i32, m: u8) -> u8 {
    match m {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 => {
            if is_leap(y) {
                29
            } else {
                28
            }
        }
        _ => 30,
    }
}

/// Format an axis tick at the given granularity.
fn tick_label(dt: &PrimitiveDateTime, u: Unit) -> String {
    let mon = MON[(u8::from(dt.month()) as usize).saturating_sub(1).min(11)];
    match u {
        Unit::Years => format!("{}", dt.year()),
        // Show the year on the January tick so a multi-year axis reads.
        Unit::Months => {
            if dt.month() == Month::January {
                format!("{} {}", mon, dt.year())
            } else {
                mon.to_string()
            }
        }
        Unit::Weeks | Unit::Days => format!("{} {}", dt.day(), mon),
        Unit::Hours => format!("{:02}:00", dt.hour()),
        Unit::Minutes => format!("{:02}:{:02}", dt.hour(), dt.minute()),
    }
}
