#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Extract workspace crate dependencies from `cargo metadata` into
data/generated/cargo.wcl: `relation` blocks between the WAD's container ids,
so the system's container diagram stays honest against Cargo.toml (the
crates are containers, so the diagram *is* the crate dependency picture)."""

import json
import subprocess
import sys
from pathlib import Path

WAD_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WAD_ROOT.parent
OUT = WAD_ROOT / "data" / "generated" / "cargo.wcl"

# Crate name -> WAD container id. Extend when the workspace grows; a crate
# missing here is skipped (extractors never invent architecture ids).
CRATE_TO_CONTAINER = {
    "wcl": "wcl_cli",
    "wcl_lang": "wcl_lang",
    "wcl_wdoc": "wcl_wdoc",
    "wcl_lsp": "wcl_lsp",
}


def wcl_str(s: str) -> str:
    """Quote a Python string as a WCL string literal."""
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def main() -> int:
    meta = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--no-deps"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    by_id = {p["id"]: p for p in meta["packages"]}
    members = sorted(
        (by_id[mid] for mid in meta["workspace_members"]), key=lambda p: p["name"]
    )
    member_names = {p["name"] for p in members}

    lines = [
        "// GENERATED by scripts/extract_cargo.py — do not hand-edit; re-run `just wad-extract`.",
        "// Source: cargo metadata (workspace root)",
        "namespace wcl.wad",
        "",
    ]

    # Workspace-internal dependency edges, as container relations.
    for pkg in members:
        src = CRATE_TO_CONTAINER.get(pkg["name"])
        if src is None:
            continue
        internal = sorted(
            d["name"]
            for d in pkg["dependencies"]
            if d["name"] in member_names and d["kind"] is None
        )
        for dep in internal:
            dst = CRATE_TO_CONTAINER.get(dep)
            if dst is None or dst == src:
                continue
            data = f"{pkg['name']} depends on {dep} (Cargo.toml)"
            lines += [
                f"relation r_gen_{src}_{dst} {{",
                f"  source = {src}  destination = {dst}",
                '  kind = :depends_on  protocol = "Rust crate"',
                f"  data = {wcl_str(data)}",
                "}",
                "",
            ]


    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
