#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Extract CI pipelines from .github/workflows/*.yml into
data/generated/ci.wcl: one `pipeline` block per workflow, one
`pipeline_stage` per job, the stage DAG from `needs:`, and gates from
job-level `if:` conditions."""

import re
import sys
from pathlib import Path

import yaml

WAD_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WAD_ROOT.parent
WORKFLOWS = REPO_ROOT / ".github" / "workflows"
OUT = WAD_ROOT / "data" / "generated" / "ci.wcl"


def wcl_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def trigger_text(on) -> str:
    """Summarise a workflow's `on:` section as one line."""
    if isinstance(on, str):
        return on
    if isinstance(on, list):
        return " / ".join(str(x) for x in on)
    parts = []
    for event, spec in (on or {}).items():
        bits = [str(event)]
        if isinstance(spec, dict):
            if "branches" in spec:
                bits.append("to " + ", ".join(spec["branches"]))
            if "paths" in spec:
                bits.append("touching " + ", ".join(spec["paths"]))
        parts.append(" ".join(bits))
    return " / ".join(parts)


def main() -> int:
    lines = [
        "// GENERATED by scripts/extract_ci.py — do not hand-edit; re-run `just wad-extract`.",
        "// Source: .github/workflows/*.yml",
        "namespace wcl.wad",
        "",
    ]
    for wf_path in sorted(WORKFLOWS.glob("*.yml")):
        wf = yaml.safe_load(wf_path.read_text())
        pid = slug(wf_path.stem)
        name = wf.get("name", wf_path.stem)
        # PyYAML parses the bare key `on:` as boolean True.
        trigger = trigger_text(wf.get("on", wf.get(True, {})))
        jobs = wf.get("jobs", {})

        # Stage DAG: job X `needs` Y  ⇒  Y.next += X.
        nxt: dict[str, list[str]] = {j: [] for j in jobs}
        for job_id, job in jobs.items():
            needs = job.get("needs", [])
            if isinstance(needs, str):
                needs = [needs]
            for n in needs:
                if n in nxt:
                    nxt[n].append(job_id)

        lines += [
            f"pipeline {pid} {{",
            f"  name    = {wcl_str(name)}",
            "  repo    = wcl_monorepo",
            f"  trigger = {wcl_str(trigger)}",
            f"  summary = {wcl_str(f'Extracted from .github/workflows/{wf_path.name}')}",
        ]
        for job_id in jobs:
            job = jobs[job_id]
            gates = []
            if "if" in job:
                gates.append(str(job["if"]).strip())
            strategy = job.get("strategy", {})
            if "matrix" in strategy:
                gates.append("matrix build")
            gate_txt = ", ".join(wcl_str(g) for g in gates)
            next_txt = ", ".join(f"st_{pid}_{slug(j)}" for j in sorted(nxt[job_id]))
            # What the job actually does: its named steps, in order (the
            # per-stage detail sections on the pipeline page render this).
            steps = [
                str(st["name"]).strip()
                for st in job.get("steps", [])
                if isinstance(st, dict) and st.get("name")
            ]
            summary = " → ".join(steps) if steps else None
            lines += [
                f"  pipeline_stage st_{pid}_{slug(job_id)} {{",
                f"    name = {wcl_str(job.get('name', job_id))}",
            ]
            if summary:
                lines.append(f"    summary = {wcl_str(summary)}")
            if gate_txt:
                lines.append(f"    gates = [{gate_txt}]")
            if next_txt:
                lines.append(f"    next = [{next_txt}]")
            lines.append("  }")
        lines += ["}", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
