#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Extract the dev-command catalogue from the justfile into
data/generated/justfile.wcl: one `dev_command` block (a WAD extension block,
see schema/extensions.wcl) per public recipe, with the doc comment as the
description and the `[group(...)]` attribute as the category.

Modules (`mod ci '.just/ci'`) are walked too, under their `mod::recipe`
invocation. A module recipe that shares its name with a root one is the SAME
recipe reached twice — .just/shared.just is imported by both — so it is listed
once, under the root name."""

import json
import re
import subprocess
import sys
from pathlib import Path

WAD_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WAD_ROOT.parent
OUT = WAD_ROOT / "data" / "generated" / "justfile.wcl"

BANNER = (
    "// GENERATED by scripts/extract_justfile.py — do not hand-edit; re-run `just wad-extract`.\n"
    "// Source: the justfile and its modules (`just --dump --dump-format json`)\n"
    "namespace wcl.wad\n"
)


def wcl_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def invocation(path: str, recipe: dict) -> str:
    parts = [f"just {path}"]
    for p in recipe.get("parameters", []):
        name = p["name"].upper()
        if p.get("kind") in ("star", "plus"):
            parts.append(f"[{name}]...")
        elif p.get("default") is not None:
            parts.append(f"[{name}]")
        else:
            parts.append(f"<{name}>")
    return " ".join(parts)


def public_recipes(
    node: dict,
    root_names: set[str],
    out: list[tuple[str, dict]],
    prefix: str = "",
) -> None:
    """Collect (invocation path, recipe) for a justfile node and its modules.

    The path is what you type: `check` at the root, `ci::check` in a module."""
    for r in node.get("recipes", {}).values():
        if r.get("private") or r["name"].startswith("_"):
            continue
        if prefix and r["name"] in root_names:
            continue  # imported from shared.just — already listed at the root
        out.append((prefix + r["name"], r))
    for name, m in node.get("modules", {}).items():
        public_recipes(m, root_names, out, f"{prefix}{name}::")


def group_of(recipe: dict) -> str | None:
    for attr in recipe.get("attributes", []):
        if isinstance(attr, dict) and "group" in attr:
            return attr["group"]
    return None


def main() -> int:
    # A justfile is required input; if `just` is missing or the dump fails,
    # write the empty placeholder and succeed, like the other extractors.
    try:
        raw = subprocess.run(
            ["just", "--dump", "--dump-format", "json"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        dump = json.loads(raw)
    except (subprocess.CalledProcessError, FileNotFoundError, json.JSONDecodeError) as e:
        print(f"could not dump the justfile ({e}) — writing the empty placeholder", file=sys.stderr)
        OUT.write_text(BANNER)
        return 0

    root_names = {r["name"] for r in dump.get("recipes", {}).values()}
    recipes: list[tuple[str, dict]] = []
    public_recipes(dump, root_names, recipes)
    # Grouped, then alphabetical — the order the Dev-commands table reads in.
    recipes.sort(key=lambda pr: (group_of(pr[1]) or "~", pr[0]))

    lines = [BANNER]
    for path, r in recipes:
        doc = (r.get("doc") or "").strip() or "(undocumented)"
        group = group_of(r)
        body = [
            f"dev_command dev_{slug(path)} {{",
            f"  name        = {wcl_str(path)}",
            f"  command     = {wcl_str(invocation(path, r))}",
            f"  description = {wcl_str(doc)}",
        ]
        if group is not None:
            body.append(f"  category    = {wcl_str(group)}")
        body.append("}")
        body.append("")
        lines.append("\n".join(body))
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)} ({len(recipes)} recipes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
