#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Extract the dev-command catalogue from the root justfile into
data/generated/justfile.wcl: one `dev_command` block (a WAD extension block,
see schema/extensions.wcl) per public recipe, with the doc comment as the
description and the `[group(...)]` attribute as the category."""

import json
import re
import subprocess
import sys
from pathlib import Path

WAD_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WAD_ROOT.parent
OUT = WAD_ROOT / "data" / "generated" / "justfile.wcl"

BANNER = (
    "// GENERATED by scripts/extract_justfile.py — do not hand-edit; re-run `just wad-extract`.\n"
    "// Source: the root justfile (`just --dump --dump-format json`)\n"
    "namespace wcl.wad\n"
)


def wcl_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def invocation(recipe: dict) -> str:
    parts = [f"just {recipe['name']}"]
    for p in recipe.get("parameters", []):
        name = p["name"].upper()
        if p.get("kind") in ("star", "plus"):
            parts.append(f"[{name}]...")
        elif p.get("default") is not None:
            parts.append(f"[{name}]")
        else:
            parts.append(f"<{name}>")
    return " ".join(parts)


def group_of(recipe: dict) -> str | None:
    for attr in recipe.get("attributes", []):
        if isinstance(attr, dict) and "group" in attr:
            return attr["group"]
    return None


def main() -> int:
    # A justfile is required input; if `just` is missing or the dump fails,
    # write the empty placeholder and succeed, like the other extractors.
    try:
        raw = subprocess.run(
            ["just", "--dump", "--dump-format", "json"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        dump = json.loads(raw)
    except (subprocess.CalledProcessError, FileNotFoundError, json.JSONDecodeError) as e:
        print(f"could not dump the justfile ({e}) — writing the empty placeholder", file=sys.stderr)
        OUT.write_text(BANNER)
        return 0

    recipes = [
        r
        for r in dump.get("recipes", {}).values()
        if not r.get("private") and not r["name"].startswith("_")
    ]
    # Grouped, then alphabetical — the order the Dev-commands table reads in.
    recipes.sort(key=lambda r: (group_of(r) or "~", r["name"]))

    lines = [BANNER]
    for r in recipes:
        doc = (r.get("doc") or "").strip() or "(undocumented)"
        group = group_of(r)
        body = [
            f"dev_command dev_{slug(r['name'])} {{",
            f"  name        = {wcl_str(r['name'])}",
            f"  command     = {wcl_str(invocation(r))}",
            f"  description = {wcl_str(doc)}",
        ]
        if group is not None:
            body.append(f"  category    = {wcl_str(group)}")
        body.append("}")
        body.append("")
        lines.append("\n".join(body))
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)} ({len(recipes)} recipes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
