#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Extract released versions from git tags into data/generated/releases.wcl:
one `release` block per `v*` tag, dated from the tag, with the commit
subjects between it and the previous tag as highlights."""

import re
import subprocess
import sys
from pathlib import Path

WAD_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WAD_ROOT.parent
OUT = WAD_ROOT / "data" / "generated" / "releases.wcl"

RELEASES_URL = "https://github.com/wiltaylor/wcl/releases/tag"
MAX_RELEASES = 20
MAX_HIGHLIGHTS = 8


def wcl_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, check=True, capture_output=True, text=True
    ).stdout


def main() -> int:
    lines = [
        "// GENERATED by scripts/extract_releases.py — do not hand-edit; re-run `just wad-extract`.",
        "// Source: git tags (v*) and the commit subjects between them",
        "namespace wcl.wad",
        "",
    ]
    # Oldest → newest so each tag's range has a well-defined predecessor;
    # emitted newest-first (the order the releases table wants).
    # Outside a git repository (or with git missing) there is nothing to
    # extract — write the placeholder and succeed, like the other extractors.
    try:
        raw_tags = git(
            "tag", "--list", "v*", "--sort=creatordate", "--format=%(refname:strip=2)\t%(creatordate:short)"
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("not inside a git repository — writing the empty placeholder", file=sys.stderr)
        OUT.write_text(
            "// GENERATED by scripts/extract_releases.py — do not hand-edit; re-run `just wad-extract`.\n"
            "// Source: git tags (no repository found)\n"
            "namespace wcl.wad\n"
        )
        return 0
    tags = [t for t in raw_tags.splitlines() if t.strip()]
    parsed = [tuple(t.split("\t", 1)) for t in tags]
    blocks: list[str] = []
    prev: str | None = None
    for tag, date in parsed:
        span = f"{prev}..{tag}" if prev else tag
        subjects = [
            s for s in git("log", "--format=%s", span).splitlines() if s.strip()
        ]
        subjects.reverse()  # oldest change first reads as a changelog
        shown = subjects[:MAX_HIGHLIGHTS]
        if len(subjects) > MAX_HIGHLIGHTS:
            shown.append(f"… and {len(subjects) - MAX_HIGHLIGHTS} more changes")
        body = [
            f"release rel_{slug(tag)} {{",
            f"  version = {wcl_str(tag)}",
            f"  date    = {wcl_str(date)}",
            "  repo    = wcl_monorepo",
            f"  summary = {wcl_str(f'{len(subjects)} changes since {prev}' if prev else f'{len(subjects)} changes (first tagged release)')}",
            "  highlights = [",
            *[f"    {wcl_str(s)}," for s in shown],
            "  ]",
            f"  url     = {wcl_str(f'{RELEASES_URL}/{tag}')}",
            "}",
            "",
        ]
        blocks.append("\n".join(body))
        prev = tag
    # Newest first, capped — the table leads with the current release.
    for b in reversed(blocks[-MAX_RELEASES:]):
        lines.append(b)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
