#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Extract the wdoc dev server's public HTTP surface from the axum route
registrations in crates/wcl/src/serve.rs into data/generated/http_api.wcl:
one :api code_item whose api_endpoint rows are the real routes."""

import re
import sys
from pathlib import Path

WAD_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WAD_ROOT.parent
SRC = REPO_ROOT / "crates" / "wcl" / "src" / "serve.rs"
OUT = WAD_ROOT / "data" / "generated" / "http_api.wcl"

# Route path -> human summary. Extend THIS table (never the generated file)
# when a new endpoint lands; unmapped routes get a placeholder that says so.
PATH_SUMMARIES = {
    "/__wdoc_reload": "Live-reload long-poll: the injected client waits here and reloads the page when a rebuild lands.",
    "/__wdoc_rebuild": "Trigger a rebuild; scoped to the sending page's sub-site, blocks until the build finishes.",
    "/__wdoc_comment.js": "The review-comment client script (comment mode).",
    "/__wdoc_comment": "Create / list review comments in the comments.wcl sidecar.",
    "/__wdoc_review/status": "Long-poll the review handshake (agent-waiting marker).",
    "/__wdoc_review/ready": "Reviewer clicked “Send to agent” — release the blocked `wcl wdoc review`.",
    "/__wdoc_edit.js": "The WYSIWYG edit client script (edit mode).",
    "/__wdoc_editor.js": "The shared source-editor component (syntect-highlighted textarea).",
    "/__wdoc_objects": "Schema data objects for the edit panel, filtered by the page's namespace.",
    "/__wdoc_edit/add": "Insert a new block (WYSIWYG structure edit).",
    "/__wdoc_edit/delete": "Delete a block (WYSIWYG structure edit).",
    "/__wdoc_edit/field": "Rewrite one block field through the `wcl set` pipeline.",
    "/__wdoc_edit/move": "Reorder a block among its siblings.",
    "/__wdoc_object": "One schema data object's instance list for the object editor.",
    "/__wdoc_object_kinds": "The @block/@table kinds the object browser offers, namespace-filtered.",
    "/__wdoc_object_source": "An instance's raw WCL source for the text editor (byte-spliced back on save).",
    "/__wdoc_object_template": "A fresh-instance template for a schema kind (new-object flow).",
    "/__wdoc_schema": "The document's schema description backing the edit panel forms.",
    "/__wdoc_edit": "Apply a block/field/structure edit through the validating `wcl set` pipeline.",
    "/__wdoc_check": "Dry-run diagnostics for an unsaved buffer (syntax + schema errors introduced).",
    "/__wdoc_format": "Format a buffer with the `wcl fmt` core.",
    "/__wdoc_files": "File tree for the source editor, scoped to the page's owning sub-site.",
    "/__wdoc_file": "Whole-file source read/save with content-etag conflict detection.",
    "/__wdoc_highlight": "Syntax-highlight a code snippet (public wcl_wdoc::highlight_code).",
    "/__wdoc_preview": "Render the current page with unsaved buffers overlaid into a scratch dir.",
    "/__wdoc_preview/{*path}": "Serve the preview render (no reload/edit scripts injected).",
}


def wcl_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def slug(s: str) -> str:
    return re.sub(r"_+", "_", "".join(c if c.isalnum() else "_" for c in s)).strip("_")


def main() -> int:
    src = SRC.read_text()
    # `.route("path", get(...))` — the path and method may sit on the next
    # line(s), so match across whitespace.
    routes: dict[str, set[str]] = {}
    for m in re.finditer(
        r"\.route\(\s*\"([^\"]+)\"\s*,\s*(?:axum::routing::)?(get|post|put|delete)\(",
        src,
        re.DOTALL,
    ):
        routes.setdefault(m.group(1), set()).add(m.group(2).upper())

    lines = [
        "// GENERATED by scripts/extract_http_api.py — do not hand-edit; re-run `just wad-extract`.",
        "// Source: axum route registrations in crates/wcl/src/serve.rs",
        "namespace wcl.wad",
        "",
        "code_item serve_http_api {",
        "  component = cli_serve",
        '  name      = "Dev-server HTTP surface"',
        '  summary   = "The endpoints `wcl wdoc serve` exposes (extracted from the axum router; comment/edit-mode routes appear only when those flags are on)."',
        "  kind      = :api",
    ]
    for path in sorted(routes):
        methods = "/".join(sorted(routes[path]))
        summary = PATH_SUMMARIES.get(path, "(describe in extract_http_api.py's PATH_SUMMARIES)")
        lines += [
            f"  api_endpoint ep_{slug(path)} {{",
            f"    method = {wcl_str(methods)}  path = {wcl_str(path)}",
            f"    summary = {wcl_str(summary)}",
            "  }",
        ]
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)} ({len(routes)} endpoints)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
