//! The declarations the language itself ships.
//!
//! Every built-in decorator (`@block`, `@children`, `@decorator`,
//! `@default`, `@applies_to`, `@unit`, `@schemaless`, `@declares_kind`)
//! is schema'd by a synthetic `type` declaration, exactly as a host's
//! decorator would be. They are registered through
//! [`Environment::new`](super::Environment) rather than special-cased in
//! the checker, so `doc::decorators` validates a language decorator and
//! a user decorator by the same path — a decorator the language defines
//! has no powers a document could not declare for itself.
//!
//! The built-in unit types come from the embedded `lib/units.wcl`,
//! parsed once and cloned in; the decorator-position vocabulary is a
//! `symbol_set` for the same reason the schemas are types.

use crate::ast;
use crate::ast::{BuiltinType, TypeRef};
use crate::ast::{synthetic_decorator, synthetic_field, synthetic_span};

/// The always-on built-in unit types (`std.ByteSize`, `std.Distance`,
/// `std.Duration`), parsed once from the embedded `lib/units.wcl` and
/// cloned into every [`Environment::new`]. They are plain type aliases
/// carrying `@unit` decorators, injected as synthetic types so a literal
/// unit (`5MiB`) resolves with no `import`.
pub(super) fn stdlib_unit_types() -> Vec<ast::TypeDecl> {
    static UNITS: std::sync::LazyLock<Vec<ast::TypeDecl>> = std::sync::LazyLock::new(|| {
        const SRC: &str = include_str!("../../lib/units.wcl");
        let source =
            crate::parse_for_edit(SRC, "<wcl-units>").expect("built-in lib/units.wcl must parse");
        source
            .items
            .into_iter()
            .filter_map(|item| match item {
                ast::Item::TypeDecl(t) => Some(t),
                _ => None,
            })
            .collect()
    });
    UNITS.clone()
}

/// Every decorator schema the language declares for itself — the
/// `@block`, `@children`, `@unit` and friends a document can use
/// without declaring them.
pub(super) fn builtin_decorator_schemas() -> Vec<ast::TypeDecl> {
    vec![
        block_schema(),
        decorator_schema(),
        applies_to_schema(),
        unit_schema(),
        synth_decorator_schema(
            "Inline",
            "inline",
            "slot",
            TypeRef::Builtin(BuiltinType::U64),
        ),
        // `default` accepts any value; tighten the inner type when an
        // `any` builtin lands.
        default_schema(),
        synth_decorator_schema(
            "Child",
            "child",
            "kind",
            TypeRef::Builtin(BuiltinType::Identifier),
        ),
        children_schema(),
        synth_decorator_schema(
            "Table",
            "table",
            "name",
            TypeRef::Builtin(BuiltinType::Identifier),
        ),
        synth_decorator_schema(
            "Connections",
            "connections",
            "schema",
            TypeRef::Builtin(BuiltinType::Identifier),
        ),
        synth_decorator_schema(
            "DocDecorator",
            "doc",
            "text",
            TypeRef::Builtin(BuiltinType::Utf8),
        ),
        synth_decorator_schema(
            "MinDecorator",
            "min",
            "value",
            TypeRef::Builtin(BuiltinType::F64),
        ),
        synth_decorator_schema(
            "MaxDecorator",
            "max",
            "value",
            TypeRef::Builtin(BuiltinType::F64),
        ),
        synth_marker_decorator_schema("NonEmptyDecorator", "non_empty"),
        synth_decorator_schema(
            "RefDecorator",
            "ref",
            "kind",
            TypeRef::Builtin(BuiltinType::Identifier),
        ),
        synth_marker_decorator_schema("ByRefDecorator", "by_ref"),
        synth_marker_decorator_schema("DynamicDecorator", "dynamic"),
        // `@document` marks a type as the schema for the document
        // root. The single declared positional arg is ignored at
        // recognition time; only the decorator name matters.
        synth_optional_decorator_schema(
            "Document",
            "document",
            "name",
            TypeRef::Builtin(BuiltinType::Utf8),
        ),
        // The bare form opts a block or field out of strict validation;
        // `annotations = true` exempts only decorators on that node.
        schemaless_decorator_schema(),
        // `@contextual` marks a block kind whose placement is decided by
        // context rather than by kind: it is legal wherever children are
        // allowed at all, its body is not recursed into by the child
        // walk, and its children are generated by the host's
        // [`Expander`]. Same shape — only the decorator name is read.
        synth_optional_decorator_schema(
            "Contextual",
            "contextual",
            "reason",
            TypeRef::Builtin(BuiltinType::Utf8),
        ),
        // `@block_slot` marks a type used by `slot name: Type` as a nested
        // block hole rather than a scalar parameter. Hosts choose the type
        // and its accepted child vocabulary; the language only keeps the
        // declaration form host-neutral.
        synth_marker_decorator_schema("BlockSlot", "block_slot"),
        // `@declares_kind(name = 0, params = "…", body = "…")` marks a
        // block type whose *instances* declare block kinds of their own.
        // Kind lookup falls back to a schema derived from the named
        // param field, so an instance of a declared kind validates like
        // any other block. Three slots, so it gets its own literal
        // rather than the one-field helper.
        declares_kind_schema(),
    ]
}

/// Schema for `@schemaless`.
fn schemaless_decorator_schema() -> ast::TypeDecl {
    let mut reason = synthetic_field("reason", TypeRef::Builtin(BuiltinType::Utf8), true);
    reason
        .decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(0)]));
    ast::TypeDecl {
        name: vec!["Schemaless".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![
            reason,
            synthetic_field("annotations", TypeRef::Builtin(BuiltinType::Bool), true),
        ],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8("schemaless".to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Schema for `@block`.
fn block_schema() -> ast::TypeDecl {
    let mut name = synthetic_field("name", TypeRef::Builtin(BuiltinType::Identifier), false);
    name.decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(0)]));
    ast::TypeDecl {
        name: vec!["Block".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![
            name,
            synthetic_field(
                "required_children",
                TypeRef::List(Box::new(TypeRef::Builtin(BuiltinType::Utf8))),
                true,
            ),
            synthetic_field(
                "required_fields",
                TypeRef::List(Box::new(TypeRef::Builtin(BuiltinType::Utf8))),
                true,
            ),
            synthetic_field("max_children", TypeRef::Builtin(BuiltinType::U64), true),
        ],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8("block".to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Schema for `@children`.
fn children_schema() -> ast::TypeDecl {
    let mut kind = synthetic_field("kind", TypeRef::Builtin(BuiltinType::Identifier), false);
    kind.decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(0)]));
    ast::TypeDecl {
        name: vec!["Children".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![
            kind,
            synthetic_field("min", TypeRef::Builtin(BuiltinType::U64), true),
            synthetic_field("max", TypeRef::Builtin(BuiltinType::U64), true),
        ],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8("children".to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Schema for `@decorator` — the declaration that lets a document
/// declare decorators of its own.
fn decorator_schema() -> ast::TypeDecl {
    let mut name = synthetic_field("name", TypeRef::Builtin(BuiltinType::Utf8), false);
    name.decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(0)]));
    let mut repeatable = synthetic_field("repeatable", TypeRef::Builtin(BuiltinType::Bool), true);
    repeatable.default_expr = Some(ast::Expr::Bool(false));
    ast::TypeDecl {
        name: vec!["Decorator".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![name, repeatable],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8("decorator".to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Schema for `@default`.
fn default_schema() -> ast::TypeDecl {
    let mut schema = synth_decorator_schema(
        "Default",
        "default",
        "value",
        TypeRef::Builtin(BuiltinType::Utf8),
    );
    // Defaults may have any declared field type. Until WCL has an `any`
    // type, use the existing field-level escape hatch to keep this slot
    // permissive while retaining its positional shape for reflection.
    schema.fields[0]
        .decorators
        .push(synthetic_decorator("schemaless", Vec::new()));
    schema
}

/// Schema for `@applies_to`.
fn applies_to_schema() -> ast::TypeDecl {
    ast::TypeDecl {
        name: vec!["AppliesTo".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![
            synthetic_field(
                "on",
                TypeRef::List(Box::new(TypeRef::named(vec![
                    "DecoratorPosition".to_string(),
                ]))),
                false,
            ),
            synthetic_field(
                "kinds",
                TypeRef::List(Box::new(TypeRef::Builtin(BuiltinType::Utf8))),
                true,
            ),
        ],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8("applies_to".to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Schema for `@unit`.
fn unit_schema() -> ast::TypeDecl {
    let mut declaration =
        synthetic_decorator("decorator", vec![ast::Expr::Utf8("unit".to_string())]);
    declaration.named.push(ast::NamedArg {
        name: "repeatable".to_string(),
        value: ast::Expr::Bool(true),
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
    });
    let mut name = synthetic_field("name", TypeRef::Builtin(BuiltinType::Utf8), false);
    name.decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(0)]));
    let mut factor = synthetic_field("factor", TypeRef::Builtin(BuiltinType::F64), false);
    factor
        .decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(1)]));
    ast::TypeDecl {
        name: vec!["Unit".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![name, factor],
        decorators: vec![declaration],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// The `DecoratorPosition` symbol set that `@applies_to` draws its
/// values from.
pub(super) fn decorator_position_set() -> ast::SymbolSetDecl {
    const POSITIONS: [&str; 11] = [
        "field",
        "fn",
        "block",
        "type",
        "interface",
        "type_field",
        "union",
        "variant",
        "symbol_set",
        "symbol",
        "connection",
    ];
    ast::SymbolSetDecl {
        name: vec!["DecoratorPosition".to_string()],
        symbols: POSITIONS
            .into_iter()
            .map(|name| ast::SymbolEntry {
                name: name.to_string(),
                decorators: Vec::new(),
                span: synthetic_span(),
                leading_trivia: Vec::new(),
                trailing_comment: None,
            })
            .collect(),
        decorators: Vec::new(),
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Build the schema for a decorator that takes no arguments at all.
fn synth_marker_decorator_schema(type_name: &str, decorator_name: &str) -> ast::TypeDecl {
    ast::TypeDecl {
        name: vec![type_name.to_string()],
        extends: Vec::new(),
        alias: None,
        fields: Vec::new(),
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8(decorator_name.to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Schema for `@declares_kind(name = 0, params = "slots", body = "body")`.
/// `name` is the declarer's `@inline(N)` label slot carrying the declared
/// kind's name; `params` and `body` name declarer fields.
fn declares_kind_schema() -> ast::TypeDecl {
    ast::TypeDecl {
        name: vec!["DeclaresKind".to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![
            synthetic_field("name", TypeRef::Builtin(BuiltinType::U64), true),
            synthetic_field("params", TypeRef::Builtin(BuiltinType::Utf8), false),
            synthetic_field("body", TypeRef::Builtin(BuiltinType::Utf8), true),
        ],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8("declares_kind".to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Build the schema for a decorator taking one required argument.
fn synth_decorator_schema(
    type_name: &str,
    decorator_name: &str,
    field_name: &str,
    field_ty: TypeRef,
) -> ast::TypeDecl {
    let mut field = synthetic_field(field_name, field_ty, false);
    field
        .decorators
        .push(synthetic_decorator("inline", vec![ast::Expr::U64(0)]));
    ast::TypeDecl {
        name: vec![type_name.to_string()],
        extends: Vec::new(),
        alias: None,
        fields: vec![field],
        decorators: vec![synthetic_decorator(
            "decorator",
            vec![ast::Expr::Utf8(decorator_name.to_string())],
        )],
        span: synthetic_span(),
        leading_trivia: Vec::new(),
        trailing_comment: None,
        trailing_trivia: Vec::new(),
    }
}

/// Build the schema for a decorator taking one optional argument.
fn synth_optional_decorator_schema(
    type_name: &str,
    decorator_name: &str,
    field_name: &str,
    field_ty: TypeRef,
) -> ast::TypeDecl {
    let mut schema = synth_decorator_schema(type_name, decorator_name, field_name, field_ty);
    schema.fields[0].optional = true;
    schema
}
