#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = []            # add what your source needs, e.g. ["pyyaml>=6"]
# ///
"""WAD extractor template — copy to <wad>/scripts/extract_<thing>.py.

Reads ONE source of truth and fully overwrites ONE output file under
data/generated/. Keep it deterministic (sorted collections, no timestamps),
derive ids from source names, and write the banner even on an empty result.
Wire the output once with an import line in data/generated/main.wcl.
"""

import sys
from pathlib import Path

WAD_ROOT = Path(__file__).resolve().parents[1]
OUT = WAD_ROOT / "data" / "generated" / "thing.wcl"  # ← rename with the script

# Source name -> WAD block id, for anything that needs human naming.
# Customising the mapping = editing this table, not the logic.
NAME_TO_ID: dict[str, str] = {}


def wcl_str(s: str) -> str:
    """Quote a Python string as a WCL string literal."""
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def slug(s: str) -> str:
    """Derive a stable WCL identifier from a source name."""
    return "".join(c if c.isalnum() else "_" for c in s)


def main() -> int:
    lines = [
        "// GENERATED by scripts/extract_thing.py — do not hand-edit; re-run `just extract`.",
        "// Source: <name the source of truth here>",
        "namespace wcl.wad",
        "",
    ]

    # 1. Read the source of truth (subprocess, file parse, DB query, HTTP…).
    # 2. Map its records onto WAD block kinds. Example shape:
    #
    # for row in sorted(records, key=lambda r: r.name):
    #     lines += [
    #         f"relation r_gen_{slug(row.src)}_{slug(row.dst)} {{",
    #         f"  source = {slug(row.src)}  destination = {slug(row.dst)}",
    #         "  kind = :depends_on",
    #         f"  data = {wcl_str(row.detail)}",
    #         "}",
    #         "",
    #     ]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(WAD_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
