/* The structure editor for a `procedure` unit: its steps' flow-chart shapes,
   and the `from -> to` connection statements that wire them.

   Why not drag-on-canvas like a diagram? A procedure's chart is generated by
   a repeater inside `wdoc/component/process.wcl`, so every step shape shares
   ONE (file, span) — the component's — and the statements live on the
   procedure unit block, which never appears in the preview. Addressing the
   unit block directly is the only way to write them, so the editor is a list
   rather than a canvas gesture. Both write the same `connect_add` /
   `connect_remove` ops the diagram canvas uses.

   A step's `shape` decides how it draws — a `:decision` is the diamond the
   `:yes` / `:no` branches leave from — so the two belong together: changing a
   step to a decision is normally followed by wiring its branches. */

import { For, Show, createResource, createSignal } from 'solid-js';
import { Plus, Trash2 } from 'lucide-solid';
import { Button, IconButton, Select, toast } from '@forge/ui';

import { api } from '../../api';
import { cellText } from '../../preview/schemaform';
import { busy, commitOpsQuiet } from '../../state/design';

/** The kinds a step flow edge can carry — `StepFlowKind` in the wskill base
    schema. `:default` is a plain arrow; the others label their branch. */
const FLOW_KINDS = ['default', 'yes', 'no'];

/** `StepShape` in the wskill base schema — how a step draws in the chart. */
const STEP_SHAPES = ['process', 'decision', 'terminator'];

export default function FlowPanel(props) {
  const [adding, setAdding] = createSignal(null); // { from, to, kind }
  const [seq, setSeq] = createSignal(0);

  // Re-read after every write: a commit reprints the file, so the span the
  // ops address moves and the statement list has to come from disk again.
  const [src, { refetch }] = createResource(
    () => ({ file: props.file, span: props.span, seq: seq() }),
    (k) => api.blockSource({ file: k.file, span: k.span }),
  );

  const flows = () => src()?.connections ?? [];
  const steps = () => props.steps ?? [];
  const stepOptions = () => steps().map((s) => ({ value: s.id, label: s.id }));

  // Each step's own source, for its current `shape`. The graph payload lists
  // the step blocks but not their fields, so read them — one small request per
  // step, re-run after a write (a commit reprints the file and moves spans).
  const [shapes] = createResource(
    () => ({ steps: steps(), seq: seq() }),
    async (k) => {
      const out = {};
      await Promise.all(
        k.steps.map(async (st) => {
          const r = await api.blockSource({ file: st.file, span: st.span });
          if (r.ok) out[st.id] = cellText(r.cells, 'shape') || 'process';
        }),
      );
      return out;
    },
  );

  const run = async (ops, msg, file) => {
    const s = src();
    if (!s?.ok) return;
    // Only the procedure's own edits can carry its etag; a step lives in its
    // own block (usually the same file, but the span is what's addressed).
    const opts = file && file !== props.file ? {} : { etag: s.etag };
    const res = await commitOpsQuiet(file ?? props.file, ops, opts);
    if (res.ok) {
      toast(msg, { duration: 3000 });
      setSeq((n) => n + 1);
      refetch();
      props.onChange?.();
    }
  };

  const setShape = (st, shape) =>
    run(
      [{ op: 'set_field', span: st.span, field: 'shape', expr: `:${shape}` }],
      `${st.id} is now a ${shape}`,
      st.file,
    );

  const remove = (f) =>
    run(
      [{ op: 'connect_remove', span: props.span, from: f.from, to: f.to }],
      `Removed ${f.from} → ${f.to}`,
    );

  const add = () => {
    const d = adding();
    if (!d?.from || !d?.to) return;
    const op = { op: 'connect_add', span: props.span, from: d.from, to: d.to };
    if (d.kind && d.kind !== 'default') op.kind = d.kind;
    run([op], `Wired ${d.from} → ${d.to}`).then(() => setAdding(null));
  };

  return (
    <div class="ed-flow-panel">
      <div class="ed-flow-head">
        <strong>Steps</strong>
      </div>
      <ul class="ed-flow-rows">
        <For each={steps()}>
          {(st) => (
            <li class="ed-flow-row">
              <span class="ed-flow-ends" title={st.id}>
                {st.id}
              </span>
              <Select
                options={STEP_SHAPES.map((v) => ({ value: v, label: v }))}
                value={shapes()?.[st.id] ?? 'process'}
                disabled={busy() || shapes.loading}
                onChange={(v) => setShape(st, v)}
              />
            </li>
          )}
        </For>
        <Show when={steps().length === 0}>
          <li class="ed-graph-noblocks">no steps yet</li>
        </Show>
      </ul>

      <div class="ed-flow-head ed-flow-head-sep">
        <strong>Step flow</strong>
        <span class="spacer" />
        <Show when={!adding()}>
          <IconButton
            icon={Plus}
            label="Add a flow"
            disabled={busy() || steps().length < 2}
            onClick={() => setAdding({ from: '', to: '', kind: 'default' })}
          />
        </Show>
      </div>

      <Show when={src.loading}>
        <div class="ed-graph-noblocks">reading…</div>
      </Show>

      <ul class="ed-flow-rows">
        <For each={flows()}>
          {(f) => (
            <li class="ed-flow-row">
              <span class="ed-flow-ends" title={`${f.from} → ${f.to}`}>
                {f.from} → {f.to}
              </span>
              <Show when={f.kind && f.kind !== 'default'}>
                <span class="ed-flow-kind">:{f.kind}</span>
              </Show>
              <IconButton
                icon={Trash2}
                label="Remove this flow"
                disabled={busy()}
                onClick={() => remove(f)}
              />
            </li>
          )}
        </For>
        <Show when={!src.loading && flows().length === 0}>
          <li class="ed-graph-noblocks">
            no flow yet — a procedure with none renders its steps in order
          </li>
        </Show>
      </ul>

      <Show when={adding()}>
        <div class="ed-flow-add">
          <Select
            options={stepOptions()}
            value={adding().from || undefined}
            placeholder="from…"
            onChange={(v) => setAdding({ ...adding(), from: v })}
          />
          <Select
            options={stepOptions().filter((o) => o.value !== adding().from)}
            value={adding().to || undefined}
            placeholder="to…"
            onChange={(v) => setAdding({ ...adding(), to: v })}
          />
          <Select
            options={FLOW_KINDS.map((k) => ({ value: k, label: k === 'default' ? '(plain)' : `:${k}` }))}
            value={adding().kind}
            onChange={(v) => setAdding({ ...adding(), kind: v })}
          />
          <Button size="sm" variant="primary" disabled={busy() || !adding().from || !adding().to} onClick={add}>
            Add
          </Button>
          <Button size="sm" onClick={() => setAdding(null)}>
            Cancel
          </Button>
        </div>
      </Show>
    </div>
  );
}
