[package]
name = "wcl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WCL command-line interface"

[[bin]]
name = "wcl"
path = "src/main.rs"

[dependencies]
wcl_lang = { workspace = true }
clap = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
